name: npm publish

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Why triggering it manually"
        required: false
        default: "need to trigger publish workflow but don't want to create a new release"
  release:
    types: [created]

jobs:
  build-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
